config/routes.rb
Rails.application.routes.draw do
  
  get 'words/index'
  root 'staticpages#home'
  get '/about', to: 'staticpages#about'
  get '/signup', to: 'users#new'
  get '/login',   to: 'sessions#new'
  delete  '/logout',   to: 'sessions#destroy'

  resources :users
  resources :sessions, only: :create
  resources :relationships

  namespace :admin do 
    get '/home', to:'users#home'
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :categories, only: [:index]
  resources :lessons, only: [:create, :show] do 
    resources :answers
  end

  resources :words, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :description,  presence: true, length: { maximum: 150 }
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  validates :content, presence: true, length: {maximum: 50}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity, as: :action, dependent: :destroy

  def next_word
    (category.words - words).first
  end

  def lesson_results
    choices.where(correct: true).count
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
  has_one :activity, as: :action, dependent: :destroy
  after_create :relationship_activity

  private
    def relationship_activity
      create_activity(user: follower)
    end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  # REGEX = Regular expression
  # To validate correct email structure
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: {minimum: 6}, allow_nil: true
  mount_uploader :avatar, AvatarUploader

  has_many :active_relationships,  class_name: 'Relationship', 
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                  foreign_key: 'followed_id',
                                  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :lessons, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :answers, through: :lessons
  has_many :categories, through: :lessons

  def follow(user)
    following << user
  end

  def unfollow(user)
    following.destroy(user)
  end

  def following?(user)
    following.include?(user)
  end

  def lesson_taken(category_id)
    lesson = lessons.find_by(category_id:category_id)
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices
  validates :content, presence: true, length: {maximum: 50}
  validate :has_one_correct_answer
  validate :has_unique_choices

  def correct_answer
    choices.find_by(correct: true).content
  end

  private
  def has_one_correct_answer
    if choices.select{ |choices| choices.correct? }.count != 1 
      return errors.add :base, "Must have one correct choice"
    end  
  end

  def has_unique_choices
    if choices.uniq { |choice| choice.content }.count < choices.length
      return errors.add :base, "Must have unique choices"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, except: [:show, :new, :create]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @feeds = @user.activities.paginate(page: params[:page], per_page: 8).order("created_at DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @answers = current_user.answers.paginate(page: params[:page], per_page: 5)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user, classes)
    @avatar = user.avatar
    if @avatar.present?
      @avatar_user = image_tag(@avatar.url, alt: user.name, class: classes)
    else
      @avatar_user = image_tag("default-avatar.jpg", alt: user.name, class: classes)
    end
    return @avatar_user
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error")%>.
    </div>

    <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %> </li>
        <% end %>
    </ul>
    <hr>
<% end %>

app/views/shared/_feed.html.erb
<% if @feeds.any? %>
    <% @feeds.each do |activity|%>
        <% if activity.action_type == "Lesson" %>
            <div class="container mt-2">
                <div class="media">
                    <div class="media-left media-middle">
                        <% if activity.user == current_user %>
                            <%= user_avatar(current_user, 'feed-avatar mr-3') %>
                        <% else %>
                            <%= user_avatar(activity.user, 'feed-avatar mr-3') %>
                        <% end %>
                    </div>
                
                    <div class="media-body align-self-center">
                        <%= link_to_if activity.user == current_user, "You", user_path(current_user) do
                            link_to activity.user.name, user_path(activity.user.id) end %> learned 
                        <%= activity.action.lesson_results %> of 
                        <%= activity.action.words.size %> in 
                        <%= link_to activity.action.category.title, lesson_path(activity.action.id) %>
                        <div>
                            <small class="text-muted"><%= time_ago_in_words(activity.created_at) %></small>
                        </div>                                    
                    </div>
                </div>
            </div>
        <% else %>
            <div class="container mt-2">
                <div class="media">
                    <div class="media-left media-middle">
                        <% if activity.user == current_user %>
                            <%= user_avatar(current_user, 'feed-avatar mr-3') %>
                        <% else %>
                            <%= user_avatar(activity.user, 'feed-avatar mr-3') %>
                        <% end %>
                    </div>
                    <div class="media-body align-self-center">
                        <%= link_to_if activity.user == current_user, "You", user_path(current_user) do
                            link_to activity.user.name, user_path(activity.user.id) end %> followed 
                        <%= link_to activity.action.followed.name, activity.action.followed %>
                        <div>
                            <small class="text-muted"><%= time_ago_in_words(activity.created_at) %></small>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>	
    <% end %>
<% else %>
    <h3 class="text-muted text-center"> Nothing to show</h3>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer bg-light text-center">
    <div class="container">
        <span class="text-muted">All rights reserved</span>
    </div>
</footer> 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <%= link_to "Framgia E-Learning System", root_path, class: 'navbar-brand' %>

         <button class="navbar-toggler"  type="button" 
                                        data-toggle="collapse"       
                                        data-target="#navbarSupportedContent" 
                                        aria-controls="navbarSupportedContent" 
                                        aria-expanded="false" 
                                        aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

         <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav ml-auto">
                <% if logged_in? %>
                    <li class="nav-item">
                        <%= link_to "Dashboard", root_url, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Categories", categories_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Members", users_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item dropdown">
                        <%= link_to current_user.name, '#',    class: 'nav-link dropdown-toggle', 
                                                        id: 'navbarDropdown', 
                                                        role: 'button',
                                                        data: { toggle: 'dropdown' },
                                                        aria: { haspopup: 'true' },
                                                        aria: { expanded: 'false' } 
                        %>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to "Profile", edit_user_path(current_user), class: 'dropdown-item' %>
                            <%= link_to "Settings", current_user, class: 'dropdown-item' %>
                            <%= link_to "Logout", logout_path, method: :delete,  class: 'dropdown-item' %>
                            <div class="dropdown-divider"></div>
                            <%= link_to "Manage Categories", '#', class: 'dropdown-item' %>
                        </div>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Home", root_url, class: 'nav-link' %>
                    </li>

                    <li class="nav-item">
                        <%= link_to "About", '#', class: 'nav-link' %>
                    </li>
                <% end %>    
            </ul>
        </div>
    </div>
</nav> 