config/routes.rb
Rails.application.routes.draw do
  
  get 'words/index'
  root 'staticpages#home'
  get '/about', to: 'staticpages#about'
  get '/signup', to: 'users#new'
  get '/login',   to: 'sessions#new'
  delete  '/logout',   to: 'sessions#destroy'

  resources :users
  resources :sessions, only: :create
  resources :relationships

  namespace :admin do 
    get '/home', to:'users#home'
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :categories, only: [:index]
  resources :lessons, only: [:create, :show] do 
    resources :answers
  end

  resources :words, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  # REGEX = Regular expression
  # To validate correct email structure
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: {minimum: 6}, allow_nil: true
  mount_uploader :avatar, AvatarUploader

  has_many :active_relationships,  class_name: 'Relationship', 
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                  foreign_key: 'followed_id',
                                  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :lessons, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :answers, through: :lessons
  has_many :categories, through: :lessons

  def follow(user)
    following << user
  end

  def unfollow(user)
    following.destroy(user)
  end

  def following?(user)
    following.include?(user)
  end

  def lesson_taken(category_id)
    lesson = lessons.find_by(category_id:category_id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :logged_in_user
  before_action :admin_user

  def home
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def update
    @user = User.find(params[:id])
    @user.update(admin: true)

    redirect_to admin_users_url
  end

  def destroy
    @user = User.find(params[:id])
    @user.update(admin: false)

    redirect_to admin_users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, except: [:show, :new, :create]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @feeds = @user.activities.paginate(page: params[:page], per_page: 8).order("created_at DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user, classes)
    @avatar = user.avatar
    if @avatar.present?
      @avatar_user = image_tag(@avatar.url, alt: user.name, class: classes)
    else
      @avatar_user = image_tag("default-avatar.jpg", alt: user.name, class: classes)
    end
    return @avatar_user
  end
end

app/views/admin/users/home.html.erb
<div class="row administration">
    <div class="col-4 offset-4 mt-5">
        <h1 class="text-center title">Administration</h1>
        <br>
        <br>
        <div class="container text-center">
            <div class="btn-design">
                <%= link_to 'Categories', admin_categories_path , class: "btn btn-dark btn-lg" %>
                <p>You can change the categories, descriptions, words, answers and choices.</p>
                <br>
                <%= link_to 'Users', admin_users_path , class: "btn btn-dark btn-lg" %>
                <p>You can add or remove the administ-ration to users.</p>
            </div>
             <%= link_to 'Back', current_user, class: "btn btn-primary" %>
        </div>  
    </div>
</div>

app/views/admin/users/index.html.erb
<h1 class="text-center border-bottom p-4 mb-3">Users</h1>

<div class="container">
    <div class="row">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Admin</th>    
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user|%>
                    <tr>
                        <td><%= user.name %></td>
                        <td><%= user.email %></td>
                        <% if user.admin? %>
                            <td><%= link_to 'Remove', [:admin, user], method: :delete, class: "btn btn-dark text-center" %></td>
                        <% else %>
                            <td><%= link_to 'Add', admin_user_path(user), method: :patch, class: "btn btn-dark text-center" %></td>
                        <% end %>
                    </tr>
                <% end %>
            </tbody>
           
        </table>
         <%= link_to 'Back', admin_home_path, class: "btn btn-primary" %>
    </div>
</div>

<div class="paginate text-center">
    <%= will_paginate %>
</div>